module.exports = {
    extends: ['stylelint-config-standard'],
    ignoreFiles: ['assets/tailwind.output.css', 'assets/vendor-*.css', 'assets/*.min.css'],
    rules: {
        'at-rule-no-unknown': [
            true,
            {
                ignoreAtRules: [
                    'apply',
                    'config',
                    'custom-variant',
                    'import',
                    'layer',
                    'plugin',
                    'source',
                    'theme',
                    'utility',
                    'variant',
                ],
            },
        ],
        'at-rule-empty-line-before': null,
        'color-function-alias-notation': null,
        'color-function-notation': null,
        'custom-property-empty-line-before': null,
        'custom-property-pattern': null,
        'declaration-empty-line-before': null,
        'declaration-property-value-keyword-no-deprecated': null,
        'hue-degree-notation': null,
        'import-notation': null,
        'media-query-no-invalid': null,
        'media-feature-range-notation': null,
        'nesting-selector-no-missing-scoping-root': null,
        'no-descending-specificity': null,
        'no-duplicate-selectors': null,
        'no-invalid-position-at-import-rule': null,
        'no-invalid-position-declaration': null,
        'property-no-vendor-prefix': null,
        'rule-empty-line-before': null,
        'selector-class-pattern': null,
        'selector-not-notation': null,
        'value-keyword-case': null,
    },
};
